# İş akışının adı (GitHub Actions arayüzünde görünecek)
name: HD film M3U Film Listesi Guncelleyici

# Bu iş akışını tetikleyecek olaylar
on:
  # 1. Manuel olarak "Run workflow" butonu ile çalıştırmayı sağlar
  workflow_dispatch:

  # 2. Zamanlanmış görev (Cron Job)
  schedule:
    # Her gün UTC saatiyle 03:00'da (Türkiye saatiyle yaklaşık sabah 06:00) çalışır.
    # Zamanlamayı https://crontab.guru/ adresinden istediğiniz gibi ayarlayabilirsiniz.
    - cron: '0 3 * * *'

# İş akışında çalışacak görevler
jobs:
  # "update-playlist" adında bir görev tanımlıyoruz
  update-playlist:
    # Görevin çalışacağı sanal makine türü
    runs-on: ubuntu-latest

    # Görevin adımları
    steps:
      # Adım 1: Depo kodlarını sanal makineye indirir.
      # Bu sayede hdfilm.py betiğine erişebiliriz.
      - name: Depoyu Kopyala
        uses: actions/checkout@v4

      # Adım 2: Python ortamını kurar.
      - name: Python'u Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Kullanılacak Python sürümü

      # Adım 3: Python betiğinin ihtiyaç duyduğu kütüphaneleri yükler.
      - name: Gerekli Kutuphaneleri Yukle
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      # Adım 4: Python betiğini çalıştırarak movies.m3u dosyasını oluşturur/günceller.
      - name: Film Listesini Guncelle
        run: python hdfilm.py

      # Adım 5: Oluşturulan movies.m3u dosyasını depoya kaydeder (commit ve push).
      # Bu adım, depoya yazma iznini sağlar.
      - name: Guncellenen M3U Dosyasini Depoya Kaydet
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # Commit mesajı
          commit_message: "Otomatik M3U Oynatma Listesi Guncellemesi"
          # Sadece movies.m3u dosyasındaki değişiklikleri dikkate al
          file_pattern: movies.m3U
          # Commit yapan kullanıcının adı ve e-postası
          commit_user_name: GitHub Actions Bot
          commit_user_email: actions@github.com