# İş akışının adı
name: HD Film Listesi Güncelleyici

on:
  # Her 6 saatte bir otomatik olarak çalıştırır
  schedule:
    - cron: '0 */6 * * *'
  # Manuel çalıştırma butonu ekler
  workflow_dispatch:

jobs:
  update-m3u:
    runs-on: ubuntu-latest

    # Depoya yazma izni (commit ve push için zorunludur)
    permissions:
      contents: write

    steps:
      # 1. Adım: Depo dosyalarını sanal makineye indirir
      - name: Depoyu Klonla
        uses: actions/checkout@v4

      # 2. Adım: Python 3.9 ortamını kurar
      - name: Python'u Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 3. Adım: Gerekli Python kütüphanelerini yükler
      - name: Bağımlılıkları Yükle
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 aiohttp

      # 4. Adım: Python betiğini çalıştırarak m3u dosyasını oluşturur
      # Betik adının "hdfilm.py" olduğunu varsayıyoruz.
      - name: HD Film Listesini Oluştur
        run: python hdfilm.py

      # 5. Adım: Oluşturulan dosyayı yeniden adlandırır, commit'ler ve gönderir
      - name: Değişiklikleri Depoya Gönder
        run: |
          # Önce betiğin 'movies.m3u' adıyla bir dosya oluşturup oluşturmadığını kontrol et
          if [ -f "movies.m3u" ]; then
            echo "'movies.m3u' dosyası bulundu, işleme devam ediliyor."
            
            # Git için kullanıcı adı ve e-posta yapılandırması
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            
            # İstediğiniz yeni M3U dosya adı
            mv movies.m3u hdfilmler.m3u
            
            # Yeni dosyayı Git'e ekle
            git add hdfilmler.m3u
            
            # Değişiklik varsa commit at, yoksa "Değişiklik yok" mesajı bas
            git commit -m "HD film listesi güncellendi" || echo "Değişiklik yok"
            
            # Ana daldaki olası değişikliklerle çakışmayı önlemek için pull --rebase
            git pull --rebase origin main || echo "Ana depoda yeni değişiklik yok"
            
            # Değişiklikleri depoya gönder
            git push
          else
            echo "'movies.m3u' dosyası oluşturulmadı, bu nedenle commit atlanıyor."
          fi